### ISSUE TITLE
looping bug ;/

### ISSUE THREAD

**Issue by HeheheM** [Panthere/GoBot#10]
http://prntscr.com/bwk83d
what is problem?

**Comment by Rohmin** [comment]
Same here, tested on 4 and 4.5

**Comment by kingsofcoms** [comment]
i'm running v4 for the past 3 hours working fine for me.

**Comment by Panthere** [comment]
Yes, I believe it is the PTC servers.
It failed to 'connect' hence the looping.

**Comment by fluffymigs** [comment]
google and ptc accounts same error
