### ISSUE TITLE
Question possible issue...? About google and a refresh field.

### ISSUE THREAD

**Issue by markymark559** [Panthere/GoBot#101]
I am really enjoying GoBot that is for sure - but I noticed that if I click account details and I refresh the "account pokemon" field that it  works GREAT - but I noticed if when I refresh the list everything shows properly, but when I go to transfer some transfer just fine and sometimes on others It throws an error code - I'm having an issue logging in right now so I can't copy the error code.

But my other question not sure if it's a google setup or just an id10t error on my part - But Im getting repeated emails from google for verification - and it's not really asking to verify an app just for me to input my password and then it doesn't send me an email for a few hours. Is this contributing possibly for logging in issues?

**Comment by Panthere** [comment]
1. This is because of the proto updates and/or the api limits added.
2. We relog you on an invalid packet and restart the bot, if that sends an email, then that'd be why. That happens every ~30-35 minutes.
