### ISSUE TITLE
(question) Will setting my self in central park work?

### ISSUE THREAD

**Issue by Disteff** [Panthere/GoBot#105]
I thought if you sent your self too far from where you actually were youll get a soft ban sorry if this is a dumb question.

**Comment by Disteff** [comment]
I've just done it and received a soft ban how is everyone able to do this?

**Comment by RenHanglo** [comment]
You can, however you will get a soft ban the first time. Ive seen other bots use spam pokestops to lift the soft ban. You will just have to wait for it to unban you. (up to 3 hours i think)

**Comment by Panthere** [comment]
You stop all activities in your location that you're currently at.
Calculate the time difference between your current location and the destination, wait that amount of time before starting the bot in NYC.
