### ISSUE TITLE
Catch on walk

### ISSUE THREAD

**Issue by wrekt** [Panthere/GoBot#106]
not sure what I am doing wrong but if i turn off catch on walk it runs fine, it just doesnt catch much. If I turn it on I catch more, but it doesnt seem to travel to destinations very well, alot of yo yoing. any help would be greatly appreciated. the bot is awesome btw
![errors](https://cloud.githubusercontent.com/assets/20734284/17267637/486ffb6e-55c3-11e6-916e-85847aa7133e.png)

**Comment by wrekt** [comment]
now it appears i am also getting the error without catch on walk enabled, so maybe its server side?

**Comment by Disteff** [comment]
idk but i also have that same exact error so its not just you

**Comment by Panthere** [comment]
Are you sure you redownloaded the update?

**Comment by wrekt** [comment]
The one you uploaded like a day ago. I will check it in a bit

**Comment by Panthere** [comment]
Hmm, I'm not sure whether it will be possible to restart the bot from that location in the code.

**Comment by Panthere** [comment]
Ok, got a fix in place for the 11th update ;)

**Comment by wrekt** [comment]
So it is the 9th release. What do you mean? Want me to reset settings and then turn on catch on walk?

**Comment by Panthere** [comment]
The bot will include a fix in the next release.

**Comment by wrekt** [comment]
Cool man your the best
