### ISSUE TITLE
"Looping PostLogin Again"

### ISSUE THREAD

**Issue by NubinsxD** [Panthere/GoBot#109]
![1469871467112-1800165821](https://cloud.githubusercontent.com/assets/20738274/17269494/c9b42eba-5641-11e6-8dcc-0651b3c427f3.jpg)
This happens on a loop constantly, and I have no idea why, could you help me?

**Comment by flo-security** [comment]
Restarting the bot fixed for me the issue. But it is really annoying. Hope Panthere can do something about it.

**Comment by Panthere** [comment]
Restarting the bot fixed it you say?
What login type are you using?
PTC or Google?

**Comment by flo-security** [comment]
ptc

**Comment by NubinsxD** [comment]
Im using google, It didn't fix it for me though, however mine is working ace now :)

**Comment by Panthere** [comment]
It certainly has to be the servers if restarting doesn't fix it.
