### ISSUE TITLE
How does CP/IV works?

### ISSUE THREAD

**Issue by artsy23** [Panthere/GoBot#11]
For example Just Under 
Evolve Selected
------------------------------------------------------------------
|X| All
|  | Abra
|  | Aerodactyl
-------------------------------------------------------------------
|  | inverse
-------------------------------------------------------------------
Over (CP/IV)
--------------------------------------------------------------------
|      50         |        25     |                       < What and how do i set this up??.. thnks

**Comment by Hunter926** [comment]
It would make sense that CP is the CP value itself, and IV is a percentage. 
I would like to get some confirmation on this though?

**Comment by Panthere** [comment]
Ok, so evolve works on an "AND".
The left box is CP (hence the CP/IV).
The right box is IV percentage (out of 100).

If CP > RequiredCP AND IV > RequiredIV Then
Evolve();
Else
Return;

**Comment by artsy23** [comment]
oh ok thanks ill try it out
