### ISSUE TITLE
Stop button not working 100%

### ISSUE THREAD

**Issue by MtDubious** [Panthere/GoBot#13]
Sometimes when pressing the stop button, the program will continue to run. Just a little annoying; not a huge priority.

**Comment by kingsofcoms** [comment]
When you press stop you should wait a little before exiting as it walks back to the original coordinates.

I've also found it starts farming again automatically, sometimes it stops and sometimes it farms.

**Comment by Panthere** [comment]
You must wait for it to finish interactions with the pokemon or forts before it will 'walk back'.
The design is not to immediately stop whatever and start walking back. Graceful as possible.
