### ISSUE TITLE
Could I set bot to catch only some type of pokemon? (not catch and then transfer)

### ISSUE THREAD

**Issue by Chenjisihan** [Panthere/GoBot#20]

**Comment by kingsofcoms** [comment]
you can set what to catch under catch options then disable transfer of pokemons.

**Comment by Chenjisihan** [comment]
Thx sir , I did it but it still catches other types .for example I checked only Dratini (under catch seleted option) but they also catch pidgey or else
I don't sure if I did something wrong.

**Comment by Chenjisihan** [comment]
May be I ask a wrong question ,sorry for my bad english.  How to set bot to catch pokemon that  only checked in Catch List ?

THX again.

**Comment by FunctionCode** [comment]
When you set what to catch, did you click "stop" and start up the bot again? It needs to be restarted before the commands you give it work.

**Comment by Panthere** [comment]
You do not 'catch only those in list'. It catches every pokemon to transfer for XP if not on the catch list.
