### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mrdauduong2** [Panthere/GoBot#22]
hi, thanks for your work !!!
your application is so good, it is almost perfect, i used it and dont want to use another bot anymore !!
if you want, i think that it could be better. some suggestion :  
- catch pokemon faster ( another bot can make at lease 60k exp / h  but your application can make only 20k exp / h , same place, same acc ) i dont know why but can you make it faster?
- incubitor egg auto 
- can we reset the location every 1 h? because after 1 h, it can not find another pokestop and it stopped.

thanks a lot !!! and have a nice day

**Comment by Panthere** [comment]
Yes, I do know the bot is slow when it comes to catching things.
Did you have No Delay and Google Directions off?
I'm not going to add 'incubator egg auto'.
I'm also not going to reset the location after an hour. I have never had any problems with a lack of pokestops after 1 hour as it will generally find a loop between the 200-300 it finds originally.

**Comment by Panthere** [comment]
XP has been fixed.

**Comment by mrdauduong2** [comment]
thanks a lot !!! will test !
