### ISSUE TITLE
Cant change Google/Relink Google?

### ISSUE THREAD

**Issue by ShinyMK** [Panthere/GoBot#23]
Title says it all if I revoke permission in settings I cant relink it

**Comment by Panthere** [comment]
I have no idea what you mean, perhaps explain it a bit more.

**Comment by lavievn** [comment]
you mean change your account ?, go to C:\Users\username\AppData\Local\Pan_Soft... open the config file, and in the 6th line, delete text between <value> tag

**Comment by ShinyMK** [comment]
Ahh perfect, Thanks. I was looking for Config files in Roaming
