### ISSUE TITLE
Pokemon get away

### ISSUE THREAD

**Issue by Vanorummy** [Panthere/GoBot#24]
Pokemon are getting away, not getting caught. Text is green.
Sometimes nothing is getting farmed. Text is blue. 
Not sure if others are having this problem?

**Comment by Vanorummy** [comment]
Update: It is catching and farming, but inconsistently.

**Comment by condio** [comment]
@vanorummy, you were soft banned. When they detect you jumping around unrealistically, they make pokemon run away and pokestops stop working for a temporary amount of time.

Your account may now be flagged for a future permaban, so I'd advise starting a new account and playing a bit more conservatively.

**Comment by Panthere** [comment]
Softban.
