### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by lavievn** [Panthere/GoBot#30]
Add a max distance for the teleporting and radian around start point, if we dont get too far by the teleport we cant be banned.
on this version sometimes the bot move far more than 300 metters, then got delay for somes seconds (softbanned), i think best max distance  around 80~100m
sorry for bad english

**Comment by Panthere** [comment]
Teleporting is only done around the nearby pokemon, it still walks to the pokestops.
It waits 5 seconds before if it is over 100 meters (rarely is)

**Comment by lavievn** [comment]
i got over 30m then no xp and poke ran away too much :(

**Comment by Panthere** [comment]
30m for minutes? meters?

**Comment by lavievn** [comment]
oh sorry, i mean 300 meters, its not delay after teleport then try catch pokemon and farm poke stop, ofcource got nothing cause softbanned, much better if you can limit max range for teleporting.

**Comment by Panthere** [comment]
Necrobot works much the same as mine.
If the distance is greater than 100 meters then pause for x seconds.
Necro uses 15 as his x, I use 5.
