### ISSUE TITLE
Catching pokemon + Farming pokestops = less xp

### ISSUE THREAD

**Issue by unopie** [Panthere/GoBot#33]
It seems that when the bot has both checkboxes clicked, it makes less xp than when only the catch pokemon box is clicked. 

No logs, but for an example

(Only catching pokemon) Xp per hour is around 6500

(Doing both) Xp per hour is only around 3000

I could probably recreate logs. It's not like I am running the bot in a highly density area and that might be the problem.

**Comment by kingsofcoms** [comment]
when catching you'll have to stop i suppose, so some amount of time is lost here. When farming pokemons you get stardust and candy instead of XP.

**Comment by Panthere** [comment]
I'm quite sure this isn't meant to be an issue on github.
Bot produces fine XP if you are in a place where there a close pokestops and pokemon around them.
New update will fix that anyway.
