### ISSUE TITLE
Fix Keep Top Pokemon

### ISSUE THREAD

**Issue by archerne** [Panthere/GoBot#40]
I'm sure this is just me missing a setting. You are doing a great job and I greatly appreciate it by the way!

Is there a way to say I want to keep the highest CP of each no matter what, and also keep everything higher than xCP or xIV?

**Comment by ctlewis** [comment]
Sounds like this setting here is what you want.

![image](https://cloud.githubusercontent.com/assets/17432639/17178617/c2565098-53db-11e6-84a5-b73b82dcd844.png)

**Comment by archerne** [comment]
That is what I was thinking too @ctlewis, but on my version (Release 9) it is disabled and marked as bugged.
![image](https://cloud.githubusercontent.com/assets/561565/17179744/e248d6f6-53df-11e6-9d55-80e5c3ba49b4.png)

**Comment by Panthere** [comment]
It is indeed still bugged.
There is no fix for it atm.
I have not been looking at it at all.
Will do in next release.
Skipping that number on inventory returns will not help :)

**Comment by Panthere** [comment]
Fixed (hopefully) in latest (will be released soon)
