### ISSUE TITLE
iam a noob but i didnt find any link on the other version can you help me out?

### ISSUE THREAD

**Issue by zedkilltalon** [Panthere/GoBot#44]
where too get  Auth Token? it seem like u have to enter a code to a google webstie but what is it? it didnt show fully in the collected log

**Comment by rulen24** [comment]
The URL is: https://accounts.google.com/o/oauth2/device/usercode?pageId=none or https://google.com/device
Enter your code that shows in the event log there.

**Comment by zedkilltalon** [comment]
ok thanks man i worked

**Comment by rulen24** [comment]
No problem!

**Comment by Panthere** [comment]
You can resize the form and then the columns just for next time ;)
