### ISSUE TITLE
Never catching anything/Pokestops not working 

### ISSUE THREAD

**Issue by RenHanglo** [Panthere/GoBot#45]
At first i caught like 4 Pokemon in a row and my pokeballs increased quite a bit... After stopped and then starting it back up, I have yet to catch one. It always says I missed and i have 3 pokeballs left.

**Comment by ctlewis** [comment]
Sounds like you were softbanned. Wait ~30 minutes and try again. If you have teleport enabled you are more likely to get softbanned while running.

**Comment by RenHanglo** [comment]
Yep... Tried again after a little bit, thanks for the reply nonetheless.

**Comment by Panthere** [comment]
Issue resolved.
