### ISSUE TITLE
plese make an entry for searching radius

### ISSUE THREAD

**Issue by Nomaan12345** [Panthere/GoBot#48]
there is this place near san francisco which shows there are lot of pokemons there.... i have checked it through pokevision but it cant detect them because there are very few poke stops there..........i have read about it in other forums that by increasing the search radius would solve it please help

**Comment by Panthere** [comment]
I'm not even going to comment on this one.
You put yourself in the spot. It'll walk to nearby pokestops, it can't magically discover every pokestop in the world while not moving.
