### ISSUE TITLE
Spams "We are within 40 meters"

### ISSUE THREAD

**Issue by FunctionCode** [Panthere/GoBot#5]
The bot spams "We are within 40 meters of the target"

Example: http://prntscr.com/bwfpcf

**Comment by Panthere** [comment]
It does that when it is still waypointing. Probably has 30 meters to go so repeats a few more times :)
Will look into it, but it really isn't a big deal to me.

**Comment by Panthere** [comment]
Not going to be fixed anytime soon, it is quite important me-thinks.
