### ISSUE TITLE
Can't get a google code? I used to... [READ]

### ISSUE THREAD

**Issue by FriendlyGuy24** [Panthere/GoBot#52]
It was working fine but now I just get this message and can't get an actual code to pop up. Please help me here is the the message I get https://gyazo.com/2784db47f6d4ee3764cd3cc9a8f331cc

**Comment by FriendlyGuy24** [comment]
![2784db47f6d4ee3764cd3cc9a8f331cc](https://cloud.githubusercontent.com/assets/20697064/17203165/12b39dd8-54e1-11e6-9584-96e549b4ce9d.png)
here hopefully this is easier to see

**Comment by asskickrelol** [comment]
I got the same problem too

**Comment by FriendlyGuy24** [comment]
It's so frustrating please help us

**Comment by ExReservoir** [comment]
Same for me as well.

**Comment by ExReservoir** [comment]
You think Niantic's on to us?

**Comment by Panthere** [comment]
Seems like an API issue, just tried latest API with the bot and no go.
Maybe a simple secret change or something like that.
NecroBot says that the servers may be having troubles for some regions of Google and can't generate tokens.

**Comment by FriendlyGuy24** [comment]
How can we fix?

**Comment by rulen24** [comment]
Found a fix. Go to an old release and get the google auth code (or if you've had older versions, go to appdata, local, pansoft and go to the xml config file in your folder. Copy the google auth code and paste it in the new xml config for the new release.

**Comment by Panthere** [comment]
Yes, sadly the token is probably the only way.
Waiting for a fix to the api or google to fix their end.

**Comment by asskickrelol** [comment]
I tried downloading the older versions but I still unable to get the token. The older version get crashed when I entered the google account. Witch version can you find your own token?

**Comment by rulen24** [comment]
Have you downloaded the bot before?

**Comment by Panthere** [comment]
I'm going to lock this discussion as we're all aware of the problem.

We must wait for the issue to be resolved on their side. Nothing I can do here.

**Comment by Panthere** [comment]
Updated implemented, please report back with whether it's working or not.

**Comment by rulen24** [comment]
Google login is down, can't check yet.

**Comment by Panthere** [comment]
That meaning what?
Kinda strange, google should be up.

**Comment by rulen24** [comment]
https://go.jooas.com

**Comment by rulen24** [comment]
Unstable now
Keeps going down.

**Comment by Panthere** [comment]
Hmm, ok, let me know how it goes if anyone tests the login.

**Comment by rulen24** [comment]
I'll test the Auth now. Just deleting my old Auth token

**Comment by rulen24** [comment]
Nope, still not working

**Comment by rulen24** [comment]
I'll retry when online

**Comment by Panthere** [comment]
Is this on the latest latest update that I pushed just moments ago? Binaries are still under the 9th release. There is no "Auth Codes" anymore. Just your email:password.

**Comment by rulen24** [comment]
Seems to not be updating on my desktop, I'll delete all and redownload

**Comment by rulen24** [comment]
Farming 0 pokestops happening now, did login though.

**Comment by Panthere** [comment]
Yes, best to wait till the servers are a bit less clustered I think :)

**Comment by rulen24** [comment]
Same, here's a picture: http://prntscr.com/bynci1

**Comment by Panthere** [comment]
Yes, so it works fine, thank you so much for testing that!

**Comment by rulen24** [comment]
No problem.
On one of your older versions with the Auth Code it's working perfectly: http://prntscr.com/byncyw

**Comment by Panthere** [comment]
Ah, yeah, it's because you already have a token, if you deleted that it wouldn't be so happy :)
