### ISSUE TITLE
The Google device code doesn't seem to show

### ISSUE THREAD

**Issue by BobDouglas33** [Panthere/GoBot#55]
I've been looking for a way to see the code but it doesn't show me.
![Issue Image](http://i.imgur.com/HfxuST9.png)

**Comment by dlhep** [comment]
Having same problem here doesn't create code for google device

**Comment by zenlawwwwww** [comment]
happen to me also

**Comment by rulen24** [comment]
same

**Comment by Panthere** [comment]
Read the other issues.
Server issue or API issue.
Waiting for fix.
Cannot do anything.
