### ISSUE TITLE
Please, all united to do the better bot.

### ISSUE THREAD

**Issue by tr0n0s** [Panthere/GoBot#57]
Join to https://github.com/NecronomiconCoding/NecroBot/
And merge all effort of people in one bot

**Comment by dlhep** [comment]
there is no exe file on the folders

**Comment by tr0n0s** [comment]
it is, download the release of NecroBot and you will see PoGo.NecroBot.CLI.exe

**Comment by BChr96** [comment]
no there isn't

**Comment by Panthere** [comment]
I don't think people actually understand the difference between bots.
This is a bot based on an API.
Necro is a bot, based off the same API.

We are both different bots with different ideas.
Necro likes the console ideas.

I'm not going to pull request to another bot using the same API, I'd rather give a diverse range of bots.
