### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by AHoward45** [Panthere/GoBot#59]
When I hit 'Start' I got this error message
![17cd0fc801a9874ff19c38c82cf76d76](https://cloud.githubusercontent.com/assets/19636090/17215026/7db2e798-54a9-11e6-9173-905c2c61c926.png)

I had the Catch Radius for 'Catch on Walk' set to 0. I also only had Pokestops selected.

**Comment by Panthere** [comment]
Hmmh, can you try again?
Looks like the servers were just down.
You were refreshing the balls for the listview.
Remember, you have to wait until AFTER it connects to the server.
