### ISSUE TITLE
google code(release 9) NOT WORKING

### ISSUE THREAD

**Issue by sk8411blind** [Panthere/GoBot#60]
On the new release of #9, it wont give you the google code to start the bot.

thanks.
-sk8411blind

**Comment by rulen24** [comment]
We know. Read the other issue.

**Comment by Liosva** [comment]
Tested several bot's and they all don't provide google code. So i think the problem is in google, or they changed API.

**Comment by Panthere** [comment]
Try now please.
Comment here if it does not work after downloading the latest update.
