### ISSUE TITLE
No google device code

### ISSUE THREAD

**Issue by flyingtech** [Panthere/GoBot#63]
I installed the bot on a new pc.  It is running fine on my other pc, but now when i log in for the first time I dont get a device code.

Initializing Rocket logger at time 7/28/2016 10:33:52 AM...
[10:33:55] Google Token: Auth Token
[10:38:47] Starting Execute on login server: Google
**[10:38:57] Your Google Device Code is  enter it at** 
[10:38:57] Once entered, please wait for the bot to start...
[10:38:57] Stop button hit!
[10:38:57] Stop was called!

**Comment by W1-PopelierE** [comment]
the auth server needs to get fixed. this is not something this developer can do something about.

**Comment by Glowings** [comment]
Please re-download the latest release or build it from the source, This issue has been resolved in the latest commit
