### ISSUE TITLE
Release 9 - Finding nearby pokemon

### ISSUE THREAD

**Issue by Phoo7** [Panthere/GoBot#65]
Hi, and thanks for the app by the way.

I've just started to use the newest version of the software but a few things I have run into are:

1. I keep getting a netframe error popping up in a window. I can click continue and it carries on, but I thought you may want to know

2. When using the find nearby pokemon option, it seems like the character gets stuck walking in circles and never moving from that position.

Hope these help!

------
EDIT: Ok, I figured out what the problem was. I had no room for new pokemon. Missed out on an Arcanine :( haha

**Comment by Phoo7** [comment]
I need to test this, but I think the issue may have been that my poke count was full

**Comment by Panthere** [comment]
1. I am aware.
2. Heh, not sure
3. Haha, ok :)
