### ISSUE TITLE
Not detecting pokemon

### ISSUE THREAD

**Issue by Rabid85** [Panthere/GoBot#68]
Hello, I'm sorry for the bother but I am absolutely 100% new to this type of stuff.

I'm trying out the program for the first time this evening and I can't seem to locate very many pokemon (if any) in the designated area. When i look on Pokevision there are tons in my area. It seems to loop around the same area not detecting any pokemon. I know they are there because I log out of the bot and into the main game, poof there they are. However the game cant seem to detect them. I pushed the radius out to 800 meters with no teleport and while watching the map he just walks in a small square.

What do I need to do to change how this is working for me?

**Comment by Panthere** [comment]
It does not go and visit pokemon, it walks to pokestops, if there are pokemon along the way, it'll pick them up if in your settings.
