### ISSUE TITLE
Exception (Postlogin)

### ISSUE THREAD

**Issue by Disteff** [Panthere/GoBot#70]
This issue 
(https://gyazo.com/103c626018f8506764273c6fa34d3264)
Continues to happen no matter what now. It was fine before then it did the "hourly crash thing" and that begun happening. I know it says its because the servers are unstable but they are completely ok for me.

(https://gyazo.com/ef59532b6e7ff4a830b9a3d5a49b56e1) my settings

**Comment by Disteff** [comment]
Oh my god im sorry for putting that lol i didnt see dont spam git with this sorryyyy. I just went back to try and figure it out and i read that lol.

**Comment by MasterPedroPT** [comment]
HAHAHA!

**Comment by krazor8** [comment]
where did u read it??

**Comment by ExReservoir** [comment]
Your setting are gonna get you soft banned lol

**Comment by krazor8** [comment]
found mine, but why would i still be able to log into my account on my tablet but the bot cant?? tablet is working 100%

**Comment by Disteff** [comment]
Ex its actually ok so far i haven't gotten any because im staying in such a small area it doesn't do much at all youll really on get soft banned if you teleport large distances trust me i got a jail broken phone ive tested it out multiple times

**Comment by Panthere** [comment]
API updated, so will have to make another rel.
