### ISSUE TITLE
I am getting this error a lot

### ISSUE THREAD

**Issue by MasterPedroPT** [Panthere/GoBot#72]
![problem](https://cloud.githubusercontent.com/assets/20713105/17232255/ab24120e-551e-11e6-9de7-796fdbfb99ea.png)

**Comment by RenHanglo** [comment]
Same here... worked for a few hours now this pops up.

**Comment by Rabid85** [comment]
Currently have the same issue.

**Comment by Panthere** [comment]
API seems to be having issues. Going to be releasing another pre-release when I have updated.
He fixed a few things I can only assume.
