### ISSUE TITLE
Evolving and Transferring Pokemon

### ISSUE THREAD

**Issue by AHoward45** [Panthere/GoBot#77]
I got these two error messages whenever I would Evolve or Transfer a Pokemon I had caught. 

Evolve:
![evolveerror](https://cloud.githubusercontent.com/assets/19636090/17235909/d0f4cf16-5512-11e6-85d4-76ba4faf403a.png)

Transfer:
![transfererror](https://cloud.githubusercontent.com/assets/19636090/17235918/de78dc04-5512-11e6-8b5f-8d89f5df2fed.png)

**Comment by Panthere** [comment]
The servers do now limit requests, simply retry.
