### ISSUE TITLE
api addition

### ISSUE THREAD

**Issue by krazor8** [Panthere/GoBot#79]
what about each user using there own api?? like how i have to do with pokemaps?

**Comment by Panthere** [comment]
I'm not sure what you mean, explain more.

**Comment by krazor8** [comment]
essentially on the poke map i was helping developing(testing due to my computers raw power and small coding) we adding a feature to use a personal google api, not sure if its the same is this games instance. but heres a link to the tut we put up on mc's get hub page https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by Panthere** [comment]
Uhm, what?
We don't use keys for the google api.
