### ISSUE TITLE
4th release: Sorting through 0 pokemon to transfer duplicates

### ISSUE THREAD

**Issue by kingsofcoms** [Panthere/GoBot#8]
I'm getting this, Override transfer seems to work but can someone confirm this or is it just me.

http://i.imgur.com/3xjN4q3.png

**Comment by MtDubious** [comment]
May or may not be related but it doesn't seem to be transferring pokemans below the threshold set in catch selected. Here are my settings: https://gyazo.com/65eafbdcb6aa816ddff42eaf5b5c9ca6. In the event log it lists transferring them, but when I check the account details section they are still there.

**Comment by kingsofcoms** [comment]
@MtDubious if i understand correctly, with your setting not a single pokemon should be kept, all must be transfered right?

I think with that it still works like 3rd release i.e only transfer a single duplicate with lower value. another way you could try is catch all and manually transfer them later.

**Comment by kingsofcoms** [comment]
@MtDubious Are you getting the same error as me? or is the 4th release working fine for you?

**Comment by MtDubious** [comment]
@kingsofcoms yea I'm an idiot, but yea I am getting that message sometimes as well.. not like a million times like you did though

**Comment by Panthere** [comment]
Huh, strange...
It does it when you catch a pokemon and on start only.
0 means that it couldn't find any duplicates.

**Comment by MtDubious** [comment]
Mine just said sorting through 0 voltorbs(https://gyazo.com/3364a29e0eafe8a3ad546a3083ec2f3e) but I had 2 other voltorbs in inventory(https://gyazo.com/981a43df95ba7cba379d7e2e2d578d73) and it didn't transfer according to the setting(https://gyazo.com/370f6f5434dc14c8f7b9871cf9d30456) was the problem I was having I think. Maybe I messed up my settings though idk

**Comment by Panthere** [comment]
Did you refresh your view?
It does not auto-refresh.

**Comment by MtDubious** [comment]
Yea the voltorb in the second picture was from after it was caught and said transferred. 68.33% iv on both, I took the picture of the voltorbs after it counted for dupes and transferred

**Comment by kingsofcoms** [comment]
@Panthere ok, i redownloaded and unzipped fresh copy and it seems to be working now, but after every catch or transfer i get this message in a single line only, does not bother me though, seems to get the job done. :+1:

**Comment by Panthere** [comment]
Haha, @kingsofcoms I wanted to make logging as verbose as possible for my sake :)

**Comment by kingsofcoms** [comment]
@Panthere How are pokemons encountered may I ask? does it only catch that spawns near pokestops or does it sweep an entire radius from given coordinates?

**Comment by MtDubious** [comment]
Caught a pinsir 251cp and 21iv(https://gyazo.com/f33866d7ee382c0ac6b5d072249cc4c9) and it says it transferred and did the 0 duplicate line thing. And then I check the account details thing and I have the 21iv 251cp pinsir there with all my other pinsirs. 
The manual override seems to work to get rid of them though.

**Comment by kingsofcoms** [comment]
@MtDubious please screenshot of the entire setting page. lemme have a look.

**Comment by MtDubious** [comment]
https://gyazo.com/10f8966081b5a31d844bb7e7efe1ee40

**Comment by MtDubious** [comment]
Should be transferring everything it catches except for pokemon above 80iv and/or 1000cp. Either way it shouldn't be keeping the 251cp 21iv pinsir as far as I'm aware.

**Comment by MtDubious** [comment]
And with those settings it's still building up duplicate pokemon below those values: https://gyazo.com/ceee2a45380202acdece6d42496048c1

**Comment by kingsofcoms** [comment]
@MtDubious I've just encountered the same, caught Rhyhorn 16Cp 85%, says transfered (i'm like no way..!). But it's still there. i have no idea.

**Comment by MtDubious** [comment]
The transfer manual override gets rid of them, but the passive transfer after catch is having a bad time.

**Comment by Panthere** [comment]
Hmmmh....
Transferred but still there?
The fuck...
@MtDubious it will 'keep' them if it is higher than catch, catch will not immediately try to transfer them.
So catch might 'be ok' but transfer may not thus it is kept.

Can you refresh the list and still have it there?

**Comment by Panthere** [comment]
Remember, passive doesn't remove non-dupes.

**Comment by MtDubious** [comment]
https://gyazo.com/e8a79e5d3d5a65ed6aca969a4bc9c793 refreshed in gif format with time lmao. There are two pidgeys in the gif, both under the requirements and not transferred

**Comment by MtDubious** [comment]
They were both caught while it was running but my event log cleared :/

**Comment by Panthere** [comment]
Hmm, can you try set the Keep Top Pokemons to 0?

**Comment by MtDubious** [comment]
https://gyazo.com/7b7f9f07071b1cb78b027b53ae97deb5 like so?

**Comment by Panthere** [comment]
Event log is always stored in log.txt in the same directory.
I have a feeling if I skip x pokemon (which is what keep does [I hate keep]) then it will not recognize the dupes.
Yes, like that, restart the bot and start it again.

**Comment by MtDubious** [comment]
Waiting for it to catch a pokemon lmao

**Comment by kingsofcoms** [comment]
@Panthere Could you respond to my previous comment 

How are pokemons encountered may I ask? does it only catch that spawns near pokestops or does it sweep an entire radius from given coordinates?

In other words does it find every pokemon in the area?

**Comment by MtDubious** [comment]
@Panthere tried it with those settings and is now checking the 5 or so duplicates I have after every catch. https://gyazo.com/9c30349eaae07442829e5c88a1ef9e2d. I'll turn the keep top 3 back on to see if that was the issue.

**Comment by MtDubious** [comment]
[06:51:19] We caught a Staryu with CP 119 (73.33% perfection) using a ITEM_POKE_BALL
[06:51:19] Requesting GetPlayerResponse
[06:51:19] Requesting GetInventoryResponse
[06:51:19] Requesting TransferPokemonOut
[06:51:19] Requesting GetInventoryResponse
[06:51:19] Transferred Staryu with 119 CP (73.33%) (Under Requirement)
[06:51:19] Requesting GetInventoryResponse
[06:51:19] Sorting through 0 pokemon to transfer duplicates...

Log after I re-enabled the top 3 keeps. Seems to not be checking for dupes the same when the keeps is at 3 vs 0.

**Comment by MtDubious** [comment]
https://gyazo.com/9f4adaa735861383764327437581560b kept the staryu after refresh in account items

**Comment by Panthere** [comment]
Yes, it was because it kept pokemons that could be evolved on pokemon capture...

**Comment by Panthere** [comment]
There are also issues with some PTC servers I assume. AU servers are working fine here, Google works for others.
Closing this as I probably have fixed the issue.
