### ISSUE TITLE
Suggestion: Keep 1 example of each Pokemon

### ISSUE THREAD

**Issue by relaxingtomato** [Panthere/GoBot#83]
Hi, 
ty for the great work. I catch a lot of new Pokemon but the bot doesn't keep them due to the CP regulation. Can u add a function where the bot will keep at least 1 example of each Pokemon ( I think I saw such an option in NecroBot).
Ty

**Comment by Panthere** [comment]
Uh, why?
I think the options I have are just fine for players who want to farm the candies.
