### ISSUE TITLE
Tenth Release - "PokemonGO.RocketAPI.Exceptions.InvalidResponse.Exception"

### ISSUE THREAD

**Issue by sparkshunter** [Panthere/GoBot#84]
1, This always popup every 10-20min, when click continue, bot won't starting, i need to quit and restart the bot.

<a href='https://postimg.org/image/qld6x8hbb/' target='_blank'><img src='https://s31.postimg.org/qld6x8hbb/1469775890157.jpg' border='0' alt='postimage'/></a>

------------------------------------------------------------------------------------------------------
2, Question : How "transfer selected" in pokemonsettingTAB works? when i uncheck, seems like they still transfer pokemon at EventLog, 

<a href='https://postimg.org/image/q8wvbjbrl/' target='_blank'><img src='https://s32.postimg.org/q8wvbjbrl/1469776843626.jpg' border='0' alt='postimage'/></a>

in case : if i dont have charmander, i unchecked it, but when they caught, its still trasferred. even its high CP.

*thanks btw, this the best bot i ever seen. user friendly with simple GUI.

**Comment by Disteff** [comment]
Check what you have your "catch" cp and iv it says teh rest will be transferred. and your lucky to even have it somewhat working mine is just fucked on both releases lol

**Comment by Panthere** [comment]
I am well aware of the issue.
Testing a new fix as we speak.
It's to do with the API.
