### ISSUE TITLE
Doesnt register lucky eggs as items?

### ISSUE THREAD

**Issue by demonslay677** [Panthere/GoBot#86]
The bot says there are no lucky eggs in your bag except there is when i log into the game on my phone, 
so the issue is the button for lucky eggs doesnt work and the eggs dont pop up in the inventory either

very good work otherwise though,  well done!

**Comment by Panthere** [comment]
Hmm, will look into it.

**Comment by Panthere** [comment]
Lucky Eggs are registering in the latest POGOProtocols I think.
They work fine too.

**Comment by demonslay677** [comment]
thank you sir
