### ISSUE TITLE
Pre-release 10 can't login - exception

### ISSUE THREAD

**Issue by adskimomo** [Panthere/GoBot#90]
Can't log in with new email/pass auth.
Login exception: PokemonGo.RocketAPI.Exceptions.GoogleException: Needs Browser at .... In C:\Users\DEDI-ADL-07\Documents\Github\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Log

Also is there data stored in a users appdata that I can erase to clear historical settings/Data?

**Comment by Panthere** [comment]
API issue, waiting for a fix.
Yes, you can clear the user settings under Pan_Soft in Local Appdata.
