### ISSUE TITLE
Pre Release 10: Error during transfer

### ISSUE THREAD

**Issue by Effesus** [Panthere/GoBot#91]
When transferring certain pokemon through the bot I receive errors, however this only happens occasionally. The following image is a screenshot of the error. #

![gobot001](https://cloud.githubusercontent.com/assets/20722355/17245235/788c3ec0-557d-11e6-8bc9-a0347171e54a.png)

**Comment by adskimomo** [comment]
It seems a common issue with issues #89 to #91:-
C:\Users\DEDI-ADL-07\.......

**Comment by Effesus** [comment]
Yeah possibly, I've just had another error, reading slightly different on a few lines.

![gobot002](https://cloud.githubusercontent.com/assets/20722355/17245785/0fb2993c-5580-11e6-9cdb-c6236fe8e50b.png)

**Comment by Panthere** [comment]
It is because of the limiting and issues to do with the API.
I have pushed a dirty fix for core bot functions, but this will not fix things like this.
Waiting on a proper update from Ferox.
