### ISSUE TITLE
at the 10th update

### ISSUE THREAD

**Issue by Jaulustus** [Panthere/GoBot#93]
I have tryed the newest update and have this error (i live in austria and the servers are Stable)

> Initializing Rocket logger at time 29.07.2016 01:53:18...
> [13:53:18] Google Token: Auth Token
> [13:53:45] Starting Execute on login server: Ptc
> [13:53:48] Sorting through 0 pokemon to evolve...
> [13:53:50] Sorting through 0 pokemon to transfer duplicates...
> [13:53:50] Farming 0 PokeStops... True
> [13:54:03] Looping PostLogin Again - Idle: False
> [13:54:03] If this is happening a lot it means the Pokemon servers are unstable, do not spam issues on git with this! We can't fix it!
> [13:54:04] Sorting through 0 pokemon to evolve...
> [13:54:05] Sorting through 0 pokemon to transfer duplicates...
> [13:54:05] Farming 0 PokeStops... True
> [13:54:16] Looping PostLogin Again - Idle: False
> [13:54:16] If this is happening a lot it means the Pokemon servers are unstable, do not spam issues on git with this! We can't fix it!

**Comment by Panthere** [comment]
Did you bother to... read... the log...?
