### ISSUE TITLE
Catching Pokemon Nearby But Doesn't

### ISSUE THREAD

**Issue by sambreaker20** [Panthere/GoBot#95]
Hello, I don't know if my settings are set up correctly but there were a lot of times where it said it was going to catch pokemon but didn't. screen shot below. I started using the bot around the 7th or 8th released and caught a ton of pokemon however now Im catching far less. Thank you for taking the time.

![untitled](https://cloud.githubusercontent.com/assets/20725622/17250204/ef64029a-5568-11e6-92da-4ce1c6186456.jpg)

**Comment by Panthere** [comment]
Can you post the exact full message?

**Comment by sambreaker20** [comment]
Im sorry that message have not popped up for a while, maybe it was fixed?

**Comment by sambreaker20** [comment]
another issue I noticed is, if you have Catch Pokémon Nearby on Walk clicked, you don't farm Pokestops anymore.

**Comment by Panthere** [comment]
Hmm, I farm pokestops fine with catch nearby on ,_,

**Comment by sambreaker20** [comment]
Ill try it with teleport, the message came back up

![untitled](https://cloud.githubusercontent.com/assets/20725622/17253863/25e409fa-5578-11e6-8ccb-b3d8461ebad7.png)

**Comment by IIOOOII** [comment]
Maybe is related to the recent changes in the range?

Now its 70 meters and not 100 meters how it was before.

SOURCE:[https://www.reddit.com/r/pokemongodev/comments/4v73aj/psa_scan_radius_was_changed_from_100m_to_70m/](url)

**Comment by Panthere** [comment]
Guys, if it says 0 pokemon nearby it means there are no pokemon nearby, it is not a 'serious bug' it simply tells you what it sees (which is nothing).
