### ISSUE TITLE
Invalid email/username for Google Authentication

### ISSUE THREAD

**Issue by jink144** [Panthere/GoBot#97]
With this newer release, how do you sign in with google?

I tried

username2
hunter2

and

username2@gmail.com
hunter2

Both do not work. Thanks for the releases.

**Comment by adskimomo** [comment]
for me this worked - https://github.com/Panthere/GoBot/issues/94

**Comment by jink144** [comment]
I believe it is because I have 2-step verification on google.

**Comment by adskimomo** [comment]
then that solution should work, it did for me. good luck

**Comment by Minnette** [comment]
Unfortunately doesn't work for all gmail accounts :(. Any institution gmail account requires a second page of authentication when logging in. The code worked when that was up and running, but app passwords (or disabling 2 step) does not.

**Comment by sh4t** [comment]
I disabled 2 factor and it is not working, though this build worked fine last night.

**Comment by jink144** [comment]
I also disabled 2 factor and it is still not working. Older version are not working either for any of my gmail accounts.

**Comment by adskimomo** [comment]
I kept 2fa on account and added an app password in google account settings and this worked for me. maybe its not the 2fa and only the app password method... might be worth a try? obviously not the institution gmail accounts tho only std.

**Comment by sh4t** [comment]
I decided to go and login via my phone and it forced logged me out and said I needed to log back in; did so -- in fact did it on all my accounts using gmail and now the GoBot binary works fine again.  It seems I had to reuth- with google on all the accounts manually before it would work.

That doesn't mean it is 100% resolved as now I just get the tons of spamming niantic server warnings.

**Comment by Panthere** [comment]
I'm not an expert on Google Authentication Methods.
I can't tell you what's wrong.
All I know is if it contains special characters (your password) then it probably will not work.
App passwords might help.

**Comment by jink144** [comment]
Thanks to all your help, I was able to get it working.

First, I logged onto the server using my phone for 5 minutes.
Second, I made an app password at: https://security.google.com/settings/security/apppasswords
Lastly, I entered email2@gmail.com for the email and the 16 character app password I made into the bot and it worked.

It seems that you must do step one in order for the bot to work.
