### ISSUE TITLE
Keeps Correcting Location to Exact Cordinates

### ISSUE THREAD

**Issue by tyrowe01** [Panthere/GoBot#98]
Whenever I want to catch a pokemon it will start that action, get close, and then correct location to exact cordinates so nothing happens, I know this is probably a setting issue, I will upload screenshots of the lines of commands, and my settings.
![5fb013da4bf93a31f8f2bd5842e8c5d0](https://cloud.githubusercontent.com/assets/20730042/17259953/c620cb92-559b-11e6-8f8b-8beea09314ae.png)
![299b423dae8cad96405cce61cfe830a3](https://cloud.githubusercontent.com/assets/20730042/17259981/dfe218a6-559b-11e6-8be0-56297f4e60f6.png)
![f7ac477366b346e51e277c2b406f179d](https://cloud.githubusercontent.com/assets/20730042/17259999/ef7783e6-559b-11e6-99f2-3b2e1fa0b5e6.png)
![1f6a79432fc84d8ced3f652b6ddcf0f1](https://cloud.githubusercontent.com/assets/20730042/17260005/fbda28b4-559b-11e6-81b9-18b51bc15039.png)

**Comment by Panthere** [comment]
It's perfectly normal, it's because Google directions doesn't take you EXACTLY to the pokestop so we have to correct it to be within 30 meters :)
